CREATE DATABASE AP103ImdbDb

USE AP103ImdbDb

CREATE TABLE Directors(
	Id INT PRIMARY KEY IDENTITY,
	Fullname NVARCHAR(100) NOT NULL
)

CREATE TABLE Movies(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(120) NOT NULL UNIQUE,
	RealeseDate DATETIME2 DEFAULT GETDATE(),
	Duration INT NOT NULL,
	Description NVARCHAR(500) NOT NULL,
	ImdbPoint FLOAT NOT NULL CHECK(ImdbPoint >= 0),
	DirectorId INT FOREIGN KEY REFERENCES Directors(Id)
)

CREATE TABLE Genres(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE MovieGenres(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT FOREIGN KEY REFERENCES Movies(Id),
	GenreId INT FOREIGN KEY REFERENCES Genres(Id)
)

CREATE TABLE Actors(
	Id INT PRIMARY KEY IDENTITY,
	Fullname NVARCHAR(150) NOT NULL
)

CREATE TABLE MovieActors(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT FOREIGN KEY REFERENCES Movies(Id),
	ActorId INT FOREIGN KEY REFERENCES Actors(Id)
)
CREATE VIEW v_GetFullMoviesDetail
AS
SELECT M.Name 'Movie', 
	   M.ImdbPoint,
	   G.Name 'Genre',
	   D.Fullname 'Director',
	   A.Fullname 'Actor' 
FROM Movies AS M
JOIN MovieGenres AS MG
ON MG.MovieId = M.Id
JOIN Genres AS G
ON MG.GenreId = G.Id
JOIN Directors AS D
ON M.DirectorId = D.Id
JOIN MovieActors AS MA
ON MA.MovieId = M.Id
JOIN Actors AS A
ON MA.ActorId = A.Id

SELECT * FROM v_GetFullMoviesDetail
WHERE ImdbPoint >= 8.7